### ISSUE TITLE
Incomplete Scryfall data prevents django from starting

### ISSUE THREAD

**Issue by davidianstyle** [chilli-axe/mpc-autofill#100]
```
docker-django-1         | Retrieve double-faced cards from Scryfall...
docker-django-1         | Querying Scryfall for DFC pairs...
docker-django-1         | Identified 313 double-faced cards
docker-django-1         | Identified 18 meld pieces
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 21, in <module>
docker-django-1         |     main()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 17, in main
docker-django-1         |     execute_from_command_line(sys.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
docker-django-1         |     utility.execute()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
docker-django-1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
docker-django-1         |     self.execute(*args, **cmd_options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
docker-django-1         |     output = self.handle(*args, **options)
docker-django-1         |   File "/MPCAutofill/MPCAutofill/cardpicker/management/commands/update_dfcs.py", line 13, in handle
docker-django-1         |     sync_dfcs()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/cardpicker/dfc_pairs.py", line 57, in sync_dfcs
docker-django-1         |     card_part_singleton_list = list(filter(lambda part: part["name"] == item["name"], item["all_parts"]))
docker-django-1         | KeyError: 'all_parts'
docker-django-1 exited with code 1
```

The Brothers' War [BRO] preview data returned from `https://api.scryfall.com/cards/search?q=is:meld` looks like it's not yet complete thus breaking Django ([Argoth, Sanctum of Nature](https://scryfall.com/card/bro/256a/argoth-sanctum-of-nature) card data doesn't contain key `all_parts`). There should probably be a warning here instead of a hard error.

**Comment by ndepaola** [comment]
fixed in the mentioned PR, thank you for your contribution!
