### ISSUE TITLE
FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist

### ISSUE THREAD

**Issue by davidianstyle** [chilli-axe/mpc-autofill#101]
Clean setup:
- `MPCAutofill/client_secrets.json` exists and populated
- `MPCAutofill/drives.csv` exists and populated
- `MPCAutofill/MPCAutofill/.env` file exists and populated
- In `docker` directory, ran `./docker_clean_all.bat`
- In `docker` directory, ran `docker compose up --build`

Full error message:
`django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist`

Maybe the `django/Dockerfile` needs a step to generate `/MPCAutofill/MPCAutofill/card_db.db`? Does the `update_database.sh` script do this?

Full log:
```
docker-django-1         | 14 static files copied to '/MPCAutofill/static', 140 unmodified, 107 post-processed.
docker-postgres-1       | 2022-10-30 02:27:34.289 UTC [29] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | psycopg2.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | 
docker-django-1         | The above exception was the direct cause of the following exception:
docker-django-1         | 
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 21, in <module>
docker-django-1         |     main()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 17, in main
docker-django-1         |     execute_from_command_line(sys.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
docker-django-1         |     utility.execute()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
docker-django-1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
docker-django-1         |     self.execute(*args, **cmd_options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
docker-django-1         |     output = self.handle(*args, **options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 96, in wrapped
docker-django-1         |     res = handle_func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
docker-django-1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
docker-django-1         |     self.loader = MigrationLoader(self.connection)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
docker-django-1         |     self.build_graph()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
docker-django-1         |     self.applied_migrations = recorder.applied_migrations()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
docker-django-1         |     if self.has_table():
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
docker-django-1         |     with self.connection.cursor() as cursor:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 323, in cursor
docker-django-1         |     return self._cursor()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
docker-django-1         |     self.ensure_connection()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 281, in ensure_connection
docker-django-1         |     with self.wrap_database_errors:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
docker-django-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | Migrate Django database...
docker-postgres-1       | 2022-10-30 02:27:35.539 UTC [30] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | psycopg2.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1         | 
docker-django-1         | The above exception was the direct cause of the following exception:
docker-django-1         | 
docker-django-1         | Traceback (most recent call last):
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 21, in <module>
docker-django-1         |     main()
docker-django-1         |   File "/MPCAutofill/MPCAutofill/manage.py", line 17, in main
docker-django-1         |     execute_from_command_line(sys.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
docker-django-1         |     utility.execute()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
docker-django-1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
docker-django-1         |     self.execute(*args, **cmd_options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
docker-django-1         |     output = self.handle(*args, **options)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 96, in wrapped
docker-django-1         |     res = handle_func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
docker-django-1         |     executor = MigrationExecutor(connection, self.migration_progress_callback)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
docker-django-1         |     self.loader = MigrationLoader(self.connection)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
docker-django-1         |     self.build_graph()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
docker-django-1         |     self.applied_migrations = recorder.applied_migrations()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
docker-django-1         |     if self.has_table():
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
docker-django-1         |     with self.connection.cursor() as cursor:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 323, in cursor
docker-django-1         |     return self._cursor()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
docker-django-1         |     self.ensure_connection()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 281, in ensure_connection
docker-django-1         |     with self.wrap_database_errors:
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
docker-django-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
docker-django-1         |     self.connect()
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 263, in connect
docker-django-1         |     self.connection = self.get_new_connection(conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
docker-django-1         |     return func(*args, **kwargs)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
docker-django-1         |     connection = Database.connect(**conn_params)
docker-django-1         |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
docker-django-1         |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-django-1         | django.db.utils.OperationalError: connection to server at "postgres" (172.24.0.3), port 5432 failed: FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
docker-django-1         | 
docker-django-1 exited with code 1
```

**Comment by ndepaola** [comment]
could you try merging master on this repo into your fork and see if that resolves the issue? I think this is because .env.dist didn't include setting the database engine to postgres like the old env.txt did, which I fixed after merging your PR

**Comment by davidianstyle** [comment]
My [`main` branch](https://github.com/davidianstyle/mpc-autofill) seems to be up-to-date with your `master` branch:
`This branch is up to date with chilli-axe/mpc-autofill:master.`

**Comment by ndepaola** [comment]
could you paste the contents of your `MPCAutofill/MPCAutofill/.env` file? (scrubbing out any personal information ofc)

**Comment by davidianstyle** [comment]
```
# SECURITY WARNING: don't run with the debug turned on in production!
DJANGO_DEBUG=True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=dstylz

# Google tag for analytics
GTAG=your_gtag

# Change allowed hosts to * to allow outside access
ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.20,146.115.41.232,mpc.dstylz.com
PREPEND_WWW=False

# Postgres Database, create username/pass for security
DATABASE_ENGINE=django.db.backends.postgresql
DATABASE_USER=mpcautofill
DATABASE_PASSWORD=mpcautofill
DATABASE_HOST=postgres
DATABASE_PORT=5432

# By default, Django will send system email from root@localhost.
# However, some mail providers reject all email from this address.
TARGET_EMAIL=dchang@davidianstyle.com

# Localization
LANG_CODE=en-us
TIME_ZONE=America/New_York

# Elasticsearch
ELASTICSEARCH_HOST=elasticsearch

# Static directory
STATIC=static

# Unique site information
SITE_NAME=MPC Autofill
REDDIT=https://www.reddit.com/r/mpcproxies/
DISCORD=https://discord.gg/Mjhgd2TW3F
THEME=pulse
```

**Comment by davidianstyle** [comment]
`docker-postgres-1` container logs:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-10-30 03:56:39.150 UTC [1] LOG:  starting PostgreSQL 13.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
2022-10-30 03:56:39.150 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-10-30 03:56:39.150 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-10-30 03:56:39.158 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-10-30 03:56:39.176 UTC [21] LOG:  database system was shut down at 2022-10-30 03:55:52 UTC
2022-10-30 03:56:39.187 UTC [1] LOG:  database system is ready to accept connections
2022-10-30 03:57:23.018 UTC [29] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
2022-10-30 03:57:24.216 UTC [30] FATAL:  database "/MPCAutofill/MPCAutofill/card_db.db" does not exist
```

Taking out `DATABASE_ENGINE=django.db.backends.postgresql` from my `.env` file seemed to fix it.

Maybe I have something else configured incorrectly?

**Comment by MrTeferi** [comment]
There is indeed a missing env variable, DATABASE_NAME, the proposed PR should fix this!
