### ISSUE TITLE
Reconsider finish modeling / Foil should not be selectable for P10 card stock.

### ISSUE THREAD

**Issue by linrav** [chilli-axe/mpc-autofill#64]
Current handling of the combination of P10 and  foil is not possible on the UI and causes the below described crash.

As an alternative, consider just modeling all the finishes allowed for each card stock and allowing the user to chose these directly as opposed to having a single toggle for foil which searches

Related driver code https://github.com/chilli-axe/mpc-autofill/blob/aaf5f5655c7f389aef3c047373f0a6504cfac349/autofill/src/driver.py#L254

```
Your order has a total of 500 cards, in the MPC bracket of up to 504 cards.
(P10) Plastic cardstock (foil).
An uncaught exception occurred: Message: element not interactable: Element is not currently visible and may not be manipulated
  (Session info: chrome=XXX.X.XXXX.XXX)
Stacktrace:
Backtrace:
        Ordinal0 [0x00697413+2389011]
        Ordinal0 [0x00629F61+1941345]
        Ordinal0 [0x0051C658+837208]
        Ordinal0 [0x0051F064+847972]
        Ordinal0 [0x0051EF22+847650]
        Ordinal0 [0x0051F1B0+848304]
        Ordinal0 [0x0054CC05+1035269]
        Ordinal0 [0x0054051E+984350]
        Ordinal0 [0x0056414C+1130828]
        Ordinal0 [0x0053F974+981364]
        Ordinal0 [0x00564364+1131364]
        Ordinal0 [0x00574302+1196802]
        Ordinal0 [0x00563F66+1130342]
        Ordinal0 [0x0053E546+976198]
        Ordinal0 [0x0053F456+980054]
        GetHandleVerifier [0x00849632+1727522]
        GetHandleVerifier [0x008FBA4D+2457661]
        GetHandleVerifier [0x0072EB81+569713]
        GetHandleVerifier [0x0072DD76+566118]
        Ordinal0 [0x00630B2B+1968939]
        Ordinal0 [0x00635988+1989000]
        Ordinal0 [0x00635A75+1989237]
        Ordinal0 [0x0063ECB1+2026673]
        BaseThreadInitThunk [0x7687FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76FD7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x76FD7A4E+238]

Press Enter to exit.cTraceback (most recent call last):
  File "autofill.py", line 17, in main
  File "src\driver.py", line 348, in execute
  File "src\driver.py", line 255, in define_order
  File "selenium\webdriver\support\select.py", line 212, in _setSelected
  File "selenium\webdriver\remote\webelement.py", line 81, in click
  File "selenium\webdriver\remote\webelement.py", line 710, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
```

Sorry in advance for not following any issue template, I tried to find guidance but likely missed it.

**Comment by ndepaola** [comment]
fixed by @chakeson in these two PRs https://github.com/chilli-axe/mpc-autofill/pull/88 https://github.com/chilli-axe/mpc-autofill/pull/90 :)
